### PR TITLE
Introduce &productnameshort; entity

### PR DESCRIPTION
**Pull request by tomschr**
### Description

Introduce `&productnameshort;` entity as discussed in SLE Writers Call on 2022-11-21.

Christoph, I'm not completely sure about the abbreviation. Maybe there isn't an (semi-)official one. Perhaps check with people who might know.

### Are there any relevant issues/feature requests?

* DOCTEAM-828

### CODE REVIEW

**Comment by cwickert** [comment]
I don't like "PC" as abbreviation. Note that currently the productname is "SUSE Linux Enterprise", since this guide is for the whole SLE family. Maybe it should be "SUSE Linux Enterprise in Public Clouds" instead. 
At that point, productnameshort would just become "SLE in public clouds".

Does this make sense or is it still too long? I'll discuss it with @kvanderveer later today.

**Comment by tomschr** [comment]
Thanks Christoph.

> I don't like "PC" as abbreviation. 

I don't like "PC" either, but I had to start at some point. :wink: That's also why this PR is on draft state.

Currently, it seems there does not exist an (semi-)official abbreviation.


> Note that currently the productname is "SUSE Linux Enterprise", since this guide is for the whole SLE family. Maybe it should be "SUSE Linux Enterprise in Public Clouds" instead.

Keep in mind: this has to be an _abbreviation_ or an _acronym_ not a full product description. We need the abbreviated form for SEO reasons (in titles, Twitter cards etc.)

**Comment by cwickert** [comment]
My suggestion for productnameshort was "SLE in Public Clouds", not "SUSE Linux Enterprise in Public Clouds".

I don't see how we can make it any shorter and I doubt we have to. Twitter cards titles are truncated at 70 chars, we are well below that. "SLES-PC" IHMO only make sense for if people actually used that acronym for searches. Otherwise switching to an abbreviated titles is counterproductive for SEO.

**Comment by tomschr** [comment]
> I don't see how we can make it any shorter and I doubt we have to. Twitter cards titles are truncated at 70 chars, we are well below that.

Believe me, we have to. Ask Jana. Every character counts. Twitter cards was just an example. It's not about the abbreviated product name alone. That would indeed fit into the limit. We have to combine with other information like the title _and_ the version. If you have already a long title you will reach _very soon_ the limit.

But I agree with you there might be no better abbreviated product name in this case.

**Review by cwickert — APPROVED** [review]
I talked to @kvanderveer and she suggested "SLE CSP" (Cloud Service Provider). I'll go with that until we have something better.

**Pull request merged**
